version: "3.8"

services:
  dev:
    env_file: ./.env
    build:
      context: .
      args:
        - USERNAME=$USERNAME
    restart: always
    ports:
      - ${CONTAINER_PORT:-1022}:22
    tty: true
    stdin_open: true
