version: "3.8"

services:
  dev:
    env_file: ./.env
    build:
      context: .
      args:
        - USERNAME=${USERNAME:-user}
        - PYTHON_VERSION=${PYTHON_VERSION:-3.10.4}
    restart: always
    ports:
      - ${SSH_PORT:-8022}:22
    tty: true
    stdin_open: true
